version: '3.5'

services:
  postgres:
    container_name: postgres_lawyerin
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: lawyerin
      POSTGRES_USER: lawyerin
      POSTGRES_DB: lawyerin
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
    dbdata: