version: '3.5'

services:
  postgres:
    container_name: postgres_lawyerin
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: lawyerin
      POSTGRES_USER: lawyerin
      POSTGRES_DB: lawyerin
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
  sftp:
    image: 'drakkan/sftpgo:latest'
    ports:
      - "8080:8080"
      - "2022:2022"
      - "10080:10080"
    restart: always
    environment:
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 10080
    volumes:
      - ./db-data/sftp/:/mnt/data/
      - ./db-data/home/:/var/lib/sftpgo